# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

addons:
  apt:
    packages:
      - libnetcdf-dev
      - gcc

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  cleanup: true
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  username: __token__
  on:
    tags: true
    repo: USDA-ARS-NWRC/spatialnc
  password:
    secure: mkkVsRdaM68E8qv/ij4hiuJ+KxCm/jVxbOMRMHkgbjHkuCfziEdzWpC7/k4N5RyRqm5Ah/imhvHgeFd9aYtElFK63LgzGZJA+gwwrdivs26EiccbIUxWIA6LNqnM6p9kT28kDxACH9KfUnGl9J92PAxlewOFrLpAdgR23wmNedE6gVpnhVEc6RSN1NAyrTT1vdDeEoSf2+PYxvSEQ+xuU7eMhHWAzqmA5gD/ZNu2mzVIDgBzElf5LkXy33sZ684sd9B13MX+J6+XUsEyyryTOmFuVz9Wsups96k/llmYwodh6+RN5vVVbggiLHy+zgNS7jJH6ZwijFV2OHx+olsvqCX0Fbz/iJa8LchErkuL7ec6inYjMj4lJjBMgKybEPD1u4nRNwh5bNYS3YW0/JHqZ9ZDE01hy0PRmdH57Qf6vGKywyOQciBj3Nii7SaWq6sZum07h8IShzcU0H5WhTI1ztp9ADnIHjF/k995fo6l+F2sN5ckG98f4+zzlacQfQZAb495aYhLa9b2Oj5XlYb6xDRWT6ZbSOzZ7iFB5P8kRN1A9XxwTO20166FOflMJoEEVmmc/aN3PLK6BNB6IUKhlQYoqjQE6AcsSKbe28EPCGZUP7KsHKfGvJOvBGIwBynYzsfeFXqGcdGo7toZyzxzUOkMUHnPjxQZj/pDJmRsr78=